using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Problem2 : MonoBehaviour
{

    //Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    int sum = 2; //Adding 2 because we're missing sequence[1] in the sum
    public int[] sequence;

    void Start()
    {
        sequence = new int[500];
        sequence[0] = 1;
        sequence[1] = 2;
        int j = 1;

        for (int i = 2; j < 4000000; i++)
        {
            sequence[i] = sequence[i-1] + sequence[i-2];
            j = sequence[i];
            if (j%2 == 0)
            {
                sum += j;
            }
        }
        Debug.Log(sum);
    }
}
